### ISSUE TITLE
amypet.web requires `TKinter` module

### ISSUE THREAD

**Issue by jhuguetn** [AMYPAD/AmyPET#23]
Failed to run the web UI version of AmyPET. Looks like an additional package named `TKinter` is needed. `TKinter` is a Python interface to the Tcl/Tk toolkit. See trace below,

```
(amypet_dev) user@host:/.../tmp/amypet$ pip install amypet[web] --quiet

(amypet_dev) user@host:/.../tmp/amypet$ amypet.web
Traceback (most recent call last):
  File "/home/user/venvs/amypet_dev/bin/amypet.web", line 5, in <module>
    from amypet.web import main
  File "/home/user/venvs/amypet_dev/lib/python3.7/site-packages/amypet/web.py", line 3, in <module>
    from . import _backend_web
  File "/home/user/venvs/amypet_dev/lib/python3.7/site-packages/amypet/_backend_web.py", line 4, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'
```

I can confirm error can be suppressed by installing the missing module as follows,
```
apt-get install python3-tk
```

If such module is a requirement I would suggest noting it in the README file.

**Comment by casperdcl** [comment]
Unfortunately folder selection isn't possible in web browsers (only file selection is possible) so yes we do indeed need `tkinter`.

Again not really a problem in `conda` but yes needs mentioning in other systems.
